// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: proto/hex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type defines whether the tile is empty, a floor tile, or a wall tile.
type Type int32

const (
	// Empty is a tile without anything in it.
	Type_Empty Type = 0
	// Floor is a tile that can be walked on.
	Type_Floor Type = 1
	// Wall is a tile that blocks movement and line-of-sight.
	Type_Wall Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Empty",
		1: "Floor",
		2: "Wall",
	}
	Type_value = map[string]int32{
		"Empty": 0,
		"Floor": 1,
		"Wall":  2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hex_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_hex_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{0}
}

// Tileset defines what tileset to use in Godot.
type Tileset int32

const (
	Tileset_Dungeon Tileset = 0
	Tileset_Woods   Tileset = 1
)

// Enum value maps for Tileset.
var (
	Tileset_name = map[int32]string{
		0: "Dungeon",
		1: "Woods",
	}
	Tileset_value = map[string]int32{
		"Dungeon": 0,
		"Woods":   1,
	}
)

func (x Tileset) Enum() *Tileset {
	p := new(Tileset)
	*p = x
	return p
}

func (x Tileset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tileset) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hex_proto_enumTypes[1].Descriptor()
}

func (Tileset) Type() protoreflect.EnumType {
	return &file_proto_hex_proto_enumTypes[1]
}

func (x Tileset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tileset.Descriptor instead.
func (Tileset) EnumDescriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{1}
}

type LogLevel int32

const (
	LogLevel_Info  LogLevel = 0
	LogLevel_Debug LogLevel = -1
	LogLevel_Warn  LogLevel = 2
	LogLevel_Error LogLevel = 3
	LogLevel_Fatal LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0:  "Info",
		-1: "Debug",
		2:  "Warn",
		3:  "Error",
		4:  "Fatal",
	}
	LogLevel_value = map[string]int32{
		"Info":  0,
		"Debug": -1,
		"Warn":  2,
		"Error": 3,
		"Fatal": 4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hex_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_hex_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{2}
}

type LogSource int32

const (
	LogSource_Server LogSource = 0
	LogSource_Player LogSource = 100
	LogSource_Game   LogSource = 200
)

// Enum value maps for LogSource.
var (
	LogSource_name = map[int32]string{
		0:   "Server",
		100: "Player",
		200: "Game",
	}
	LogSource_value = map[string]int32{
		"Server": 0,
		"Player": 100,
		"Game":   200,
	}
)

func (x LogSource) Enum() *LogSource {
	p := new(LogSource)
	*p = x
	return p
}

func (x LogSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hex_proto_enumTypes[3].Descriptor()
}

func (LogSource) Type() protoreflect.EnumType {
	return &file_proto_hex_proto_enumTypes[3]
}

func (x LogSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSource.Descriptor instead.
func (LogSource) EnumDescriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{3}
}

type Result int32

const (
	Result_Unknown Result = 0
	Result_Failure Result = 1
	Result_Success Result = 2
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "Unknown",
		1: "Failure",
		2: "Success",
	}
	Result_value = map[string]int32{
		"Unknown": 0,
		"Failure": 1,
		"Success": 2,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hex_proto_enumTypes[4].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_proto_hex_proto_enumTypes[4]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{4}
}

// Coordinate is the x,y location in the world for a tile.
type Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Tile is a single tile within the world.
type Tile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type defines whether the tile is empty, a floor, or a wall.
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=endless.Type" json:"type,omitempty"`
	// Coords defines the position of the tile within the world.
	Coords *Coordinate `protobuf:"bytes,2,opt,name=coords,proto3" json:"coords,omitempty"`
}

func (x *Tile) Reset() {
	*x = Tile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{1}
}

func (x *Tile) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Empty
}

func (x *Tile) GetCoords() *Coordinate {
	if x != nil {
		return x.Coords
	}
	return nil
}

// Level is a single layer of tiles laid out to create a level.
type Level struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Tiles is an array of all the tiles laid out on a level.
	Tiles []*Tile `protobuf:"bytes,1,rep,name=tiles,proto3" json:"tiles,omitempty"`
	// Tileset tells Godot what tileset to use.
	Tileset Tileset `protobuf:"varint,2,opt,name=tileset,proto3,enum=endless.Tileset" json:"tileset,omitempty"`
}

func (x *Level) Reset() {
	*x = Level{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{2}
}

func (x *Level) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *Level) GetTileset() Tileset {
	if x != nil {
		return x.Tileset
	}
	return Tileset_Dungeon
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	At     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Level  LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=endless.LogLevel" json:"level,omitempty"`
	Source LogSource              `protobuf:"varint,4,opt,name=source,proto3,enum=endless.LogSource" json:"source,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Log) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Log) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_Info
}

func (x *Log) GetSource() LogSource {
	if x != nil {
		return x.Source
	}
	return LogSource_Server
}

type InfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{4}
}

type InfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BuildDate string `protobuf:"bytes,2,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{5}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

type GetLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLevel) Reset() {
	*x = GetLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevel) ProtoMessage() {}

func (x *GetLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevel.ProtoReflect.Descriptor instead.
func (*GetLevel) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{6}
}

type GameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Types that are assignable to Request:
	//
	//	*GameRequest_Info
	//	*GameRequest_GetLevel
	Request isGameRequest_Request `protobuf_oneof:"request"`
}

func (x *GameRequest) Reset() {
	*x = GameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRequest) ProtoMessage() {}

func (x *GameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRequest.ProtoReflect.Descriptor instead.
func (*GameRequest) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{7}
}

func (x *GameRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (m *GameRequest) GetRequest() isGameRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *GameRequest) GetInfo() *InfoRequest {
	if x, ok := x.GetRequest().(*GameRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *GameRequest) GetGetLevel() *GetLevel {
	if x, ok := x.GetRequest().(*GameRequest_GetLevel); ok {
		return x.GetLevel
	}
	return nil
}

type isGameRequest_Request interface {
	isGameRequest_Request()
}

type GameRequest_Info struct {
	Info *InfoRequest `protobuf:"bytes,2,opt,name=info,proto3,oneof"`
}

type GameRequest_GetLevel struct {
	GetLevel *GetLevel `protobuf:"bytes,3,opt,name=get_level,json=getLevel,proto3,oneof"`
}

func (*GameRequest_Info) isGameRequest_Request() {}

func (*GameRequest_GetLevel) isGameRequest_Request() {}

type GameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Types that are assignable to Msesage:
	//
	//	*GameResponse_Log
	//	*GameResponse_Info
	//	*GameResponse_Level
	Msesage isGameResponse_Msesage `protobuf_oneof:"msesage"`
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{8}
}

func (x *GameResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (m *GameResponse) GetMsesage() isGameResponse_Msesage {
	if m != nil {
		return m.Msesage
	}
	return nil
}

func (x *GameResponse) GetLog() *Log {
	if x, ok := x.GetMsesage().(*GameResponse_Log); ok {
		return x.Log
	}
	return nil
}

func (x *GameResponse) GetInfo() *InfoResponse {
	if x, ok := x.GetMsesage().(*GameResponse_Info); ok {
		return x.Info
	}
	return nil
}

func (x *GameResponse) GetLevel() *Level {
	if x, ok := x.GetMsesage().(*GameResponse_Level); ok {
		return x.Level
	}
	return nil
}

type isGameResponse_Msesage interface {
	isGameResponse_Msesage()
}

type GameResponse_Log struct {
	Log *Log `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type GameResponse_Info struct {
	Info *InfoResponse `protobuf:"bytes,3,opt,name=info,proto3,oneof"`
}

type GameResponse_Level struct {
	Level *Level `protobuf:"bytes,4,opt,name=level,proto3,oneof"`
}

func (*GameResponse_Log) isGameResponse_Msesage() {}

func (*GameResponse_Info) isGameResponse_Msesage() {}

func (*GameResponse_Level) isGameResponse_Msesage() {}

type AddTile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tile *Tile `protobuf:"bytes,1,opt,name=tile,proto3" json:"tile,omitempty"`
}

func (x *AddTile) Reset() {
	*x = AddTile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTile) ProtoMessage() {}

func (x *AddTile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTile.ProtoReflect.Descriptor instead.
func (*AddTile) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{9}
}

func (x *AddTile) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

type RemoveTile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coords *Coordinate `protobuf:"bytes,1,opt,name=coords,proto3" json:"coords,omitempty"`
}

func (x *RemoveTile) Reset() {
	*x = RemoveTile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTile) ProtoMessage() {}

func (x *RemoveTile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTile.ProtoReflect.Descriptor instead.
func (*RemoveTile) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveTile) GetCoords() *Coordinate {
	if x != nil {
		return x.Coords
	}
	return nil
}

type AdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Types that are assignable to Request:
	//
	//	*AdminRequest_AddTile
	//	*AdminRequest_RemoveTile
	Request isAdminRequest_Request `protobuf_oneof:"request"`
}

func (x *AdminRequest) Reset() {
	*x = AdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequest) ProtoMessage() {}

func (x *AdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequest.ProtoReflect.Descriptor instead.
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{11}
}

func (x *AdminRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (m *AdminRequest) GetRequest() isAdminRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *AdminRequest) GetAddTile() *AddTile {
	if x, ok := x.GetRequest().(*AdminRequest_AddTile); ok {
		return x.AddTile
	}
	return nil
}

func (x *AdminRequest) GetRemoveTile() *RemoveTile {
	if x, ok := x.GetRequest().(*AdminRequest_RemoveTile); ok {
		return x.RemoveTile
	}
	return nil
}

type isAdminRequest_Request interface {
	isAdminRequest_Request()
}

type AdminRequest_AddTile struct {
	AddTile *AddTile `protobuf:"bytes,2,opt,name=add_tile,json=addTile,proto3,oneof"`
}

type AdminRequest_RemoveTile struct {
	RemoveTile *RemoveTile `protobuf:"bytes,3,opt,name=remove_tile,json=removeTile,proto3,oneof"`
}

func (*AdminRequest_AddTile) isAdminRequest_Request() {}

func (*AdminRequest_RemoveTile) isAdminRequest_Request() {}

type AdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Log      *Log   `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Result   Result `protobuf:"varint,3,opt,name=result,proto3,enum=endless.Result" json:"result,omitempty"`
}

func (x *AdminResponse) Reset() {
	*x = AdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hex_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResponse) ProtoMessage() {}

func (x *AdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hex_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResponse.ProtoReflect.Descriptor instead.
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_hex_proto_rawDescGZIP(), []int{12}
}

func (x *AdminResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AdminResponse) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *AdminResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_Unknown
}

var File_proto_hex_proto protoreflect.FileDescriptor

var file_proto_hex_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0a, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x56, 0x0a, 0x04, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x21, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x65, 0x6e,
	0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x2b, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x58, 0x0a,
	0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x54, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x74,
	0x69, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x65,
	0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x52, 0x07,
	0x74, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x22, 0x98, 0x01, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x2a, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x61, 0x74, 0x12, 0x27, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x65,
	0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73,
	0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x47, 0x0a, 0x0c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x93, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x30, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x08, 0x67, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xad, 0x01, 0x0a,
	0x0c, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x03, 0x6c, 0x6f,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x2b, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x73, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x73, 0x65, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x54, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6c, 0x65, 0x22, 0x39, 0x0a, 0x0a, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x06, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x41, 0x64, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x54, 0x69,
	0x6c, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0a,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x75, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x03,
	0x6c, 0x6f, 0x67, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x26, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x61,
	0x6c, 0x6c, 0x10, 0x02, 0x2a, 0x21, 0x0a, 0x07, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x12,
	0x0b, 0x0a, 0x07, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x57, 0x6f, 0x6f, 0x64, 0x73, 0x10, 0x01, 0x2a, 0x48, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x05, 0x44, 0x65, 0x62, 0x75, 0x67, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x61, 0x72, 0x6e, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x61, 0x74, 0x61, 0x6c, 0x10,
	0x04, 0x2a, 0x2e, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x10, 0x64, 0x12, 0x09, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x10, 0xc8,
	0x01, 0x2a, 0x2f, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x02, 0x42, 0x8d, 0x01, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x73, 0x42, 0x08, 0x48, 0x65, 0x78, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x61, 0x6e, 0x68,
	0x61, 0x67, 0x65, 0x6e, 0x2f, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x5f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xa2, 0x02, 0x03, 0x45, 0x58, 0x58, 0xaa, 0x02,
	0x07, 0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0xca, 0x02, 0x07, 0x45, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x73, 0xe2, 0x02, 0x13, 0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x45, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_hex_proto_rawDescOnce sync.Once
	file_proto_hex_proto_rawDescData = file_proto_hex_proto_rawDesc
)

func file_proto_hex_proto_rawDescGZIP() []byte {
	file_proto_hex_proto_rawDescOnce.Do(func() {
		file_proto_hex_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_hex_proto_rawDescData)
	})
	return file_proto_hex_proto_rawDescData
}

var file_proto_hex_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_hex_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_hex_proto_goTypes = []interface{}{
	(Type)(0),                     // 0: endless.Type
	(Tileset)(0),                  // 1: endless.Tileset
	(LogLevel)(0),                 // 2: endless.LogLevel
	(LogSource)(0),                // 3: endless.LogSource
	(Result)(0),                   // 4: endless.Result
	(*Coordinate)(nil),            // 5: endless.Coordinate
	(*Tile)(nil),                  // 6: endless.Tile
	(*Level)(nil),                 // 7: endless.Level
	(*Log)(nil),                   // 8: endless.Log
	(*InfoRequest)(nil),           // 9: endless.InfoRequest
	(*InfoResponse)(nil),          // 10: endless.InfoResponse
	(*GetLevel)(nil),              // 11: endless.GetLevel
	(*GameRequest)(nil),           // 12: endless.GameRequest
	(*GameResponse)(nil),          // 13: endless.GameResponse
	(*AddTile)(nil),               // 14: endless.AddTile
	(*RemoveTile)(nil),            // 15: endless.RemoveTile
	(*AdminRequest)(nil),          // 16: endless.AdminRequest
	(*AdminResponse)(nil),         // 17: endless.AdminResponse
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_proto_hex_proto_depIdxs = []int32{
	0,  // 0: endless.Tile.type:type_name -> endless.Type
	5,  // 1: endless.Tile.coords:type_name -> endless.Coordinate
	6,  // 2: endless.Level.tiles:type_name -> endless.Tile
	1,  // 3: endless.Level.tileset:type_name -> endless.Tileset
	18, // 4: endless.Log.at:type_name -> google.protobuf.Timestamp
	2,  // 5: endless.Log.level:type_name -> endless.LogLevel
	3,  // 6: endless.Log.source:type_name -> endless.LogSource
	9,  // 7: endless.GameRequest.info:type_name -> endless.InfoRequest
	11, // 8: endless.GameRequest.get_level:type_name -> endless.GetLevel
	8,  // 9: endless.GameResponse.log:type_name -> endless.Log
	10, // 10: endless.GameResponse.info:type_name -> endless.InfoResponse
	7,  // 11: endless.GameResponse.level:type_name -> endless.Level
	6,  // 12: endless.AddTile.tile:type_name -> endless.Tile
	5,  // 13: endless.RemoveTile.coords:type_name -> endless.Coordinate
	14, // 14: endless.AdminRequest.add_tile:type_name -> endless.AddTile
	15, // 15: endless.AdminRequest.remove_tile:type_name -> endless.RemoveTile
	8,  // 16: endless.AdminResponse.log:type_name -> endless.Log
	4,  // 17: endless.AdminResponse.result:type_name -> endless.Result
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_hex_proto_init() }
func file_proto_hex_proto_init() {
	if File_proto_hex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_hex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Level); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hex_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_hex_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*GameRequest_Info)(nil),
		(*GameRequest_GetLevel)(nil),
	}
	file_proto_hex_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*GameResponse_Log)(nil),
		(*GameResponse_Info)(nil),
		(*GameResponse_Level)(nil),
	}
	file_proto_hex_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*AdminRequest_AddTile)(nil),
		(*AdminRequest_RemoveTile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_hex_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_hex_proto_goTypes,
		DependencyIndexes: file_proto_hex_proto_depIdxs,
		EnumInfos:         file_proto_hex_proto_enumTypes,
		MessageInfos:      file_proto_hex_proto_msgTypes,
	}.Build()
	File_proto_hex_proto = out.File
	file_proto_hex_proto_rawDesc = nil
	file_proto_hex_proto_goTypes = nil
	file_proto_hex_proto_depIdxs = nil
}
