run:
  timeout: 5m
  skip-dirs:
    - infra
    - sample_files
    - magefiles
  modules-download-mode: readonly

output:
  format: github-actions
  sort-results: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path-except: _test\.go
      linters:
        - forbidigo
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      source: "^//go:generate "
  exclude-use-default: false
  exclude-dirs:
    - magefiles
  exclude-dirs-use-default: false
  exclude-files:
    - magefile.go

severity:
  default-severity: error

linters:
  disable:
  enable:
    - depguard
    - musttag
    - funlen
    - forbidigo
    - gci
    - godox
    - tagalign
    - ireturn
    - nlreturn
    - wsl
    - exhaustruct
    - gochecknoglobals
    - goerr113
    - gofumpt
    - lll
    - typecheck
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
linters-settings:
  varnamelen:
    min-name-length: 2
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
