---
version: "3"

x-base: &base
  stop_signal: SIGTERM
  cpu_count: 2
  cpu_percent: 30
  cpus: 0.3
  mem_limit: 512M
  memswap_limit: 512M
  environment:
    GRPC_GO_LOG_SEVERITY_LEVEL: FATAL
    GRPC_GO_LOG_VERBOSITY_LEVEL: 0
    GRPC_GO_REQUIRE_HANDSHAKE: "off"

services:
  # database:
  #   image: postgres:11
  #   cpu_count: 1
  #   cpu_percent: 30
  #   cpus: 0.3
  #   mem_limit: 512M
  #   memswap_limit: 512M
  #   ports:
  #     - "5454:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: endless

  game_server:
    <<: *base
    command: ["/server"]
    build:
      context: backend/deploy
    ports:
      - "8000:8000"
    volumes:
      - ./backend/dev.config.yaml:/etc/es/config.yaml
