---
version: "3"

x-base: &base
  stop_signal: SIGTERM
  cpu_count: 2
  cpu_percent: 30
  cpus: 0.3
  mem_limit: 512M
  memswap_limit: 512M
  environment:
    GRPC_GO_LOG_SEVERITY_LEVEL: FATAL
    GRPC_GO_LOG_VERBOSITY_LEVEL: 0
    GRPC_GO_REQUIRE_HANDSHAKE: "off"

services:
  # database:
  #   image: postgres:11
  #   cpu_count: 1
  #   cpu_percent: 30
  #   cpus: 0.3
  #   mem_limit: 512M
  #   memswap_limit: 512M
  #   ports:
  #     - "5454:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: endless

  game_server:
    <<: *base
    command: ["/server"]
    build:
      context: backend/deploy
    ports:
      - "8000:8000"
    volumes:
      - ./backend/dev.config.yaml:/etc/es/config.yaml

  sdk-server:
    build: ./sdk-server
    network_mode: service:game_server

  nodeproxy:
    <<: *base
    build:
      context: ./node_proxy
    volumes:
      - ./node_proxy/index.js:/app/index.js
      - ./node_proxy/proto:/app/proto
    ports:
      - "8080:3000"
    depends_on:
      - game_server

  grpcweb:
    <<: *base
    image: gcr.io/cave-goblin-network/grpcweb-proxy:20200214-0
    logging:
      driver: "none"
    command: [
    "--server_tls_cert_file=/misc/localhost.crt",
    "--server_tls_key_file=/misc/localhost.key",
    "--backend_addr=game_server:8000",
    "--backend_tls_noverify",
    "--use_websockets",
    "--allow_all_origins"
    ]
    depends_on:
        - game_server
    ports:
      - "9090:8080"
      - "9443:8443"
