apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: endless-game
spec:
  template:
    spec:
      ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 8000
        protocol: TCP
      template:
        spec:
          containers:
          - name: endless-game
            image: gcr.io/cave-goblin-network/endless:latest
            imagePullPolicy: Always
            imagePullSecrets:
              - name: gcr
            resources:
              requests:
                memory: "32Mi"
                cpu: "20m"
              limits:
                memory: "32Mi"
                cpu: "20m"
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: endless-autoscaler
spec:
  fleetName: endless-game
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 0
      maxReplicas: 10
---
