// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/hex_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Endless {

  /// <summary>Holder for reflection information generated from proto/hex_service.proto</summary>
  public static partial class HexServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/hex_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HexServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdwcm90by9oZXhfc2VydmljZS5wcm90bxIHZW5kbGVzcxoPcHJvdG8vaGV4",
            "LnByb3RvMnMKA0hleBIzCgRJbmZvEhQuZW5kbGVzcy5JbmZvUmVxdWVzdBoV",
            "LmVuZGxlc3MuSW5mb1Jlc3BvbnNlEjcKBEdhbWUSFC5lbmRsZXNzLkdhbWVS",
            "ZXF1ZXN0GhUuZW5kbGVzcy5HYW1lUmVzcG9uc2UoATABMkQKBUFkbWluEjsK",
            "Bk1hbmFnZRIVLmVuZGxlc3MuQWRtaW5SZXF1ZXN0GhYuZW5kbGVzcy5BZG1p",
            "blJlc3BvbnNlKAEwAUKUAQoLY29tLmVuZGxlc3NCD0hleFNlcnZpY2VQcm90",
            "b1ABWjhnaXRodWIuY29tL3NlYW5oYWdlbi9lbmRsZXNzX3N0cmVhbS9pbnRl",
            "cm5hbC9wcm90by9wcm90b6ICA0VYWKoCB0VuZGxlc3PKAgdFbmRsZXNz4gIT",
            "RW5kbGVzc1xHUEJNZXRhZGF0YeoCB0VuZGxlc3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Endless.HexReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
