// @generated by protoc-gen-connect-web v0.8.6
// @generated from file test/test.proto (package endless, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PingReq, PongResp, TestRequest, TestResponse, TestStreamRequest, TestStreamResponse } from "./test_types_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service endless.Test
 */
export const Test = {
  typeName: "endless.Test",
  methods: {
    /**
     * @generated from rpc endless.Test.Ping
     */
    ping: {
      name: "Ping",
      I: PingReq,
      O: PongResp,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc endless.Test.ClientStream
     */
    clientStream: {
      name: "ClientStream",
      I: TestStreamRequest,
      O: TestResponse,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * @generated from rpc endless.Test.ServerStream
     */
    serverStream: {
      name: "ServerStream",
      I: TestRequest,
      O: TestStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc endless.Test.BiDiStream
     */
    biDiStream: {
      name: "BiDiStream",
      I: TestStreamRequest,
      O: TestStreamResponse,
      kind: MethodKind.ClientStreaming,
    },
  }
};
