// Code generated by protoc-gen-go. DO NOT EDIT.
// source: input.proto

package endless

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientType int32

const (
	// ClientPlayer is a client that is a player
	ClientType_ClientPlayer ClientType = 0
	// ClientAudience is a client that represents an audience member
	ClientType_ClientAudience ClientType = 1
	// ClientDisplay is a client that represents the shared info display
	ClientType_ClientDisplay ClientType = 2
)

var ClientType_name = map[int32]string{
	0: "ClientPlayer",
	1: "ClientAudience",
	2: "ClientDisplay",
}

var ClientType_value = map[string]int32{
	"ClientPlayer":   0,
	"ClientAudience": 1,
	"ClientDisplay":  2,
}

func (x ClientType) String() string {
	return proto.EnumName(ClientType_name, int32(x))
}

func (ClientType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{0}
}

type Move_Dir int32

const (
	Move_Left  Move_Dir = 0
	Move_Right Move_Dir = 1
)

var Move_Dir_name = map[int32]string{
	0: "Left",
	1: "Right",
}

var Move_Dir_value = map[string]int32{
	"Left":  0,
	"Right": 1,
}

func (x Move_Dir) String() string {
	return proto.EnumName(Move_Dir_name, int32(x))
}

func (Move_Dir) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{5, 0}
}

type Register struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 ClientType `protobuf:"varint,4,opt,name=type,proto3,enum=endless.stream.v1.ClientType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{0}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

func (m *Register) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Register) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Register) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Register) GetType() ClientType {
	if m != nil {
		return m.Type
	}
	return ClientType_ClientPlayer
}

type CharSelect struct {
	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// if nil, means they've unselected their choice
	// this allows for players to swap when all four have been selected
	Choice               *Class   `protobuf:"bytes,2,opt,name=choice,proto3" json:"choice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharSelect) Reset()         { *m = CharSelect{} }
func (m *CharSelect) String() string { return proto.CompactTextString(m) }
func (*CharSelect) ProtoMessage()    {}
func (*CharSelect) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{1}
}

func (m *CharSelect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharSelect.Unmarshal(m, b)
}
func (m *CharSelect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharSelect.Marshal(b, m, deterministic)
}
func (m *CharSelect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharSelect.Merge(m, src)
}
func (m *CharSelect) XXX_Size() int {
	return xxx_messageInfo_CharSelect.Size(m)
}
func (m *CharSelect) XXX_DiscardUnknown() {
	xxx_messageInfo_CharSelect.DiscardUnknown(m)
}

var xxx_messageInfo_CharSelect proto.InternalMessageInfo

func (m *CharSelect) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *CharSelect) GetChoice() *Class {
	if m != nil {
		return m.Choice
	}
	return nil
}

type GameStart struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStart) Reset()         { *m = GameStart{} }
func (m *GameStart) String() string { return proto.CompactTextString(m) }
func (*GameStart) ProtoMessage()    {}
func (*GameStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{2}
}

func (m *GameStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStart.Unmarshal(m, b)
}
func (m *GameStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStart.Marshal(b, m, deterministic)
}
func (m *GameStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStart.Merge(m, src)
}
func (m *GameStart) XXX_Size() int {
	return xxx_messageInfo_GameStart.Size(m)
}
func (m *GameStart) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStart.DiscardUnknown(m)
}

var xxx_messageInfo_GameStart proto.InternalMessageInfo

type UseSkill struct {
	SkillId              string   `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	TargetId             string   `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseSkill) Reset()         { *m = UseSkill{} }
func (m *UseSkill) String() string { return proto.CompactTextString(m) }
func (*UseSkill) ProtoMessage()    {}
func (*UseSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{3}
}

func (m *UseSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseSkill.Unmarshal(m, b)
}
func (m *UseSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseSkill.Marshal(b, m, deterministic)
}
func (m *UseSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseSkill.Merge(m, src)
}
func (m *UseSkill) XXX_Size() int {
	return xxx_messageInfo_UseSkill.Size(m)
}
func (m *UseSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_UseSkill.DiscardUnknown(m)
}

var xxx_messageInfo_UseSkill proto.InternalMessageInfo

func (m *UseSkill) GetSkillId() string {
	if m != nil {
		return m.SkillId
	}
	return ""
}

func (m *UseSkill) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

type UseItem struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseItem) Reset()         { *m = UseItem{} }
func (m *UseItem) String() string { return proto.CompactTextString(m) }
func (*UseItem) ProtoMessage()    {}
func (*UseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{4}
}

func (m *UseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseItem.Unmarshal(m, b)
}
func (m *UseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseItem.Marshal(b, m, deterministic)
}
func (m *UseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseItem.Merge(m, src)
}
func (m *UseItem) XXX_Size() int {
	return xxx_messageInfo_UseItem.Size(m)
}
func (m *UseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UseItem.DiscardUnknown(m)
}

var xxx_messageInfo_UseItem proto.InternalMessageInfo

func (m *UseItem) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type Move struct {
	Dir                  Move_Dir `protobuf:"varint,1,opt,name=dir,proto3,enum=endless.stream.v1.Move_Dir" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{5}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetDir() Move_Dir {
	if m != nil {
		return m.Dir
	}
	return Move_Left
}

// ActionComplete is sent by the players & status UI clients once they've all processed
// an action and updated
type ActionComplete struct {
	CompletedId          string   `protobuf:"bytes,1,opt,name=completed_id,json=completedId,proto3" json:"completed_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionComplete) Reset()         { *m = ActionComplete{} }
func (m *ActionComplete) String() string { return proto.CompactTextString(m) }
func (*ActionComplete) ProtoMessage()    {}
func (*ActionComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{6}
}

func (m *ActionComplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionComplete.Unmarshal(m, b)
}
func (m *ActionComplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionComplete.Marshal(b, m, deterministic)
}
func (m *ActionComplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionComplete.Merge(m, src)
}
func (m *ActionComplete) XXX_Size() int {
	return xxx_messageInfo_ActionComplete.Size(m)
}
func (m *ActionComplete) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionComplete.DiscardUnknown(m)
}

var xxx_messageInfo_ActionComplete proto.InternalMessageInfo

func (m *ActionComplete) GetCompletedId() string {
	if m != nil {
		return m.CompletedId
	}
	return ""
}

// Purchase is sent when a player has selected an item to buy in the store
type Purchase struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Purchase) Reset()         { *m = Purchase{} }
func (m *Purchase) String() string { return proto.CompactTextString(m) }
func (*Purchase) ProtoMessage()    {}
func (*Purchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{7}
}

func (m *Purchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Purchase.Unmarshal(m, b)
}
func (m *Purchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Purchase.Marshal(b, m, deterministic)
}
func (m *Purchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Purchase.Merge(m, src)
}
func (m *Purchase) XXX_Size() int {
	return xxx_messageInfo_Purchase.Size(m)
}
func (m *Purchase) XXX_DiscardUnknown() {
	xxx_messageInfo_Purchase.DiscardUnknown(m)
}

var xxx_messageInfo_Purchase proto.InternalMessageInfo

func (m *Purchase) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EndGame struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndGame) Reset()         { *m = EndGame{} }
func (m *EndGame) String() string { return proto.CompactTextString(m) }
func (*EndGame) ProtoMessage()    {}
func (*EndGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{8}
}

func (m *EndGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndGame.Unmarshal(m, b)
}
func (m *EndGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndGame.Marshal(b, m, deterministic)
}
func (m *EndGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndGame.Merge(m, src)
}
func (m *EndGame) XXX_Size() int {
	return xxx_messageInfo_EndGame.Size(m)
}
func (m *EndGame) XXX_DiscardUnknown() {
	xxx_messageInfo_EndGame.DiscardUnknown(m)
}

var xxx_messageInfo_EndGame proto.InternalMessageInfo

// Continue is sent when a player has acknowledged that they're ready to continue. This
// is sent when the game is in the Victory, Store, or New Wave screens so that the game
// can continue if all players have stated they're ready ( otherwise a timer will automatically
// advance to the next state )
type Continue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Continue) Reset()         { *m = Continue{} }
func (m *Continue) String() string { return proto.CompactTextString(m) }
func (*Continue) ProtoMessage()    {}
func (*Continue) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{9}
}

func (m *Continue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Continue.Unmarshal(m, b)
}
func (m *Continue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Continue.Marshal(b, m, deterministic)
}
func (m *Continue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Continue.Merge(m, src)
}
func (m *Continue) XXX_Size() int {
	return xxx_messageInfo_Continue.Size(m)
}
func (m *Continue) XXX_DiscardUnknown() {
	xxx_messageInfo_Continue.DiscardUnknown(m)
}

var xxx_messageInfo_Continue proto.InternalMessageInfo

type AudienceYell struct {
	IsCheering           bool     `protobuf:"varint,1,opt,name=is_cheering,json=isCheering,proto3" json:"is_cheering,omitempty"`
	IsBooing             bool     `protobuf:"varint,2,opt,name=is_booing,json=isBooing,proto3" json:"is_booing,omitempty"`
	Amount               int32    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudienceYell) Reset()         { *m = AudienceYell{} }
func (m *AudienceYell) String() string { return proto.CompactTextString(m) }
func (*AudienceYell) ProtoMessage()    {}
func (*AudienceYell) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{10}
}

func (m *AudienceYell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudienceYell.Unmarshal(m, b)
}
func (m *AudienceYell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudienceYell.Marshal(b, m, deterministic)
}
func (m *AudienceYell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudienceYell.Merge(m, src)
}
func (m *AudienceYell) XXX_Size() int {
	return xxx_messageInfo_AudienceYell.Size(m)
}
func (m *AudienceYell) XXX_DiscardUnknown() {
	xxx_messageInfo_AudienceYell.DiscardUnknown(m)
}

var xxx_messageInfo_AudienceYell proto.InternalMessageInfo

func (m *AudienceYell) GetIsCheering() bool {
	if m != nil {
		return m.IsCheering
	}
	return false
}

func (m *AudienceYell) GetIsBooing() bool {
	if m != nil {
		return m.IsBooing
	}
	return false
}

func (m *AudienceYell) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Input struct {
	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Types that are valid to be assigned to Input:
	//	*Input_Register
	//	*Input_CharSelect
	//	*Input_GameStart
	//	*Input_Skill
	//	*Input_Item
	//	*Input_Move
	//	*Input_ActionComplete
	//	*Input_Purchase
	//	*Input_Continue
	//	*Input_EndGame
	//	*Input_Audience
	Input                isInput_Input `protobuf_oneof:"input"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6f7669dced820e, []int{11}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type isInput_Input interface {
	isInput_Input()
}

type Input_Register struct {
	Register *Register `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type Input_CharSelect struct {
	CharSelect *CharSelect `protobuf:"bytes,20,opt,name=char_select,json=charSelect,proto3,oneof"`
}

type Input_GameStart struct {
	GameStart *GameStart `protobuf:"bytes,30,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type Input_Skill struct {
	Skill *UseSkill `protobuf:"bytes,40,opt,name=skill,proto3,oneof"`
}

type Input_Item struct {
	Item *UseItem `protobuf:"bytes,50,opt,name=item,proto3,oneof"`
}

type Input_Move struct {
	Move *Move `protobuf:"bytes,60,opt,name=move,proto3,oneof"`
}

type Input_ActionComplete struct {
	ActionComplete *ActionComplete `protobuf:"bytes,70,opt,name=action_complete,json=actionComplete,proto3,oneof"`
}

type Input_Purchase struct {
	Purchase *Purchase `protobuf:"bytes,80,opt,name=purchase,proto3,oneof"`
}

type Input_Continue struct {
	Continue *Continue `protobuf:"bytes,90,opt,name=continue,proto3,oneof"`
}

type Input_EndGame struct {
	EndGame *EndGame `protobuf:"bytes,100,opt,name=end_game,json=endGame,proto3,oneof"`
}

type Input_Audience struct {
	Audience *AudienceYell `protobuf:"bytes,110,opt,name=audience,proto3,oneof"`
}

func (*Input_Register) isInput_Input() {}

func (*Input_CharSelect) isInput_Input() {}

func (*Input_GameStart) isInput_Input() {}

func (*Input_Skill) isInput_Input() {}

func (*Input_Item) isInput_Input() {}

func (*Input_Move) isInput_Input() {}

func (*Input_ActionComplete) isInput_Input() {}

func (*Input_Purchase) isInput_Input() {}

func (*Input_Continue) isInput_Input() {}

func (*Input_EndGame) isInput_Input() {}

func (*Input_Audience) isInput_Input() {}

func (m *Input) GetInput() isInput_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Input) GetRegister() *Register {
	if x, ok := m.GetInput().(*Input_Register); ok {
		return x.Register
	}
	return nil
}

func (m *Input) GetCharSelect() *CharSelect {
	if x, ok := m.GetInput().(*Input_CharSelect); ok {
		return x.CharSelect
	}
	return nil
}

func (m *Input) GetGameStart() *GameStart {
	if x, ok := m.GetInput().(*Input_GameStart); ok {
		return x.GameStart
	}
	return nil
}

func (m *Input) GetSkill() *UseSkill {
	if x, ok := m.GetInput().(*Input_Skill); ok {
		return x.Skill
	}
	return nil
}

func (m *Input) GetItem() *UseItem {
	if x, ok := m.GetInput().(*Input_Item); ok {
		return x.Item
	}
	return nil
}

func (m *Input) GetMove() *Move {
	if x, ok := m.GetInput().(*Input_Move); ok {
		return x.Move
	}
	return nil
}

func (m *Input) GetActionComplete() *ActionComplete {
	if x, ok := m.GetInput().(*Input_ActionComplete); ok {
		return x.ActionComplete
	}
	return nil
}

func (m *Input) GetPurchase() *Purchase {
	if x, ok := m.GetInput().(*Input_Purchase); ok {
		return x.Purchase
	}
	return nil
}

func (m *Input) GetContinue() *Continue {
	if x, ok := m.GetInput().(*Input_Continue); ok {
		return x.Continue
	}
	return nil
}

func (m *Input) GetEndGame() *EndGame {
	if x, ok := m.GetInput().(*Input_EndGame); ok {
		return x.EndGame
	}
	return nil
}

func (m *Input) GetAudience() *AudienceYell {
	if x, ok := m.GetInput().(*Input_Audience); ok {
		return x.Audience
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Input) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Input_Register)(nil),
		(*Input_CharSelect)(nil),
		(*Input_GameStart)(nil),
		(*Input_Skill)(nil),
		(*Input_Item)(nil),
		(*Input_Move)(nil),
		(*Input_ActionComplete)(nil),
		(*Input_Purchase)(nil),
		(*Input_Continue)(nil),
		(*Input_EndGame)(nil),
		(*Input_Audience)(nil),
	}
}

func init() {
	proto.RegisterEnum("endless.stream.v1.ClientType", ClientType_name, ClientType_value)
	proto.RegisterEnum("endless.stream.v1.Move_Dir", Move_Dir_name, Move_Dir_value)
	proto.RegisterType((*Register)(nil), "endless.stream.v1.Register")
	proto.RegisterType((*CharSelect)(nil), "endless.stream.v1.CharSelect")
	proto.RegisterType((*GameStart)(nil), "endless.stream.v1.GameStart")
	proto.RegisterType((*UseSkill)(nil), "endless.stream.v1.UseSkill")
	proto.RegisterType((*UseItem)(nil), "endless.stream.v1.UseItem")
	proto.RegisterType((*Move)(nil), "endless.stream.v1.Move")
	proto.RegisterType((*ActionComplete)(nil), "endless.stream.v1.ActionComplete")
	proto.RegisterType((*Purchase)(nil), "endless.stream.v1.Purchase")
	proto.RegisterType((*EndGame)(nil), "endless.stream.v1.EndGame")
	proto.RegisterType((*Continue)(nil), "endless.stream.v1.Continue")
	proto.RegisterType((*AudienceYell)(nil), "endless.stream.v1.AudienceYell")
	proto.RegisterType((*Input)(nil), "endless.stream.v1.Input")
}

func init() { proto.RegisterFile("input.proto", fileDescriptor_db6f7669dced820e) }

var fileDescriptor_db6f7669dced820e = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xef, 0x6f, 0xe3, 0x34,
	0x18, 0xc7, 0xd3, 0xae, 0x3f, 0xd2, 0xa7, 0xa3, 0xf4, 0x2c, 0xc4, 0x99, 0x1e, 0x70, 0x77, 0x79,
	0x35, 0x21, 0x5d, 0x77, 0x6b, 0x85, 0xd0, 0x24, 0x26, 0xb1, 0x76, 0x83, 0x56, 0x1a, 0xd2, 0xc8,
	0xd8, 0x0b, 0xc6, 0x8b, 0xc8, 0x8d, 0x1f, 0x12, 0x6b, 0x89, 0x53, 0xc5, 0xce, 0xa4, 0xfd, 0x6d,
	0xfc, 0x73, 0xc8, 0x4e, 0xd2, 0x32, 0x48, 0xef, 0x9d, 0x9f, 0xaf, 0xbf, 0x5f, 0xfb, 0xb1, 0xfd,
	0x91, 0x61, 0x28, 0xe4, 0xb6, 0xd0, 0xd3, 0x6d, 0x9e, 0xe9, 0x8c, 0xbc, 0x42, 0xc9, 0x13, 0x54,
	0x6a, 0xaa, 0x74, 0x8e, 0x2c, 0x9d, 0x3e, 0x9d, 0x4d, 0xa0, 0xd0, 0x22, 0x29, 0xa7, 0xbd, 0x02,
	0x5c, 0x1f, 0x23, 0xa1, 0x34, 0xe6, 0x64, 0x04, 0x6d, 0xc1, 0x69, 0xeb, 0x5d, 0xeb, 0x64, 0xe0,
	0xb7, 0x05, 0x27, 0x04, 0x3a, 0x61, 0xc6, 0x91, 0xb6, 0xad, 0x62, 0xc7, 0x46, 0x93, 0x2c, 0x45,
	0x7a, 0x54, 0x6a, 0x66, 0x4c, 0xce, 0xa0, 0xa3, 0x9f, 0xb7, 0x48, 0x3b, 0xef, 0x5a, 0x27, 0xa3,
	0xd9, 0x37, 0xd3, 0xff, 0xed, 0x38, 0x5d, 0x26, 0x02, 0xa5, 0xfe, 0xfd, 0x79, 0x8b, 0xbe, 0xb5,
	0x7a, 0x7f, 0x02, 0x2c, 0x63, 0x96, 0xdf, 0x61, 0x82, 0xa1, 0x26, 0x6f, 0x60, 0xb0, 0x4d, 0xd8,
	0x33, 0xe6, 0xc1, 0x6e, 0x7f, 0xb7, 0x14, 0xd6, 0x9c, 0x7c, 0x84, 0x5e, 0x18, 0x67, 0x22, 0x2c,
	0xfb, 0x18, 0xce, 0x68, 0xe3, 0xfa, 0x4c, 0x29, 0xbf, 0xf2, 0x79, 0x43, 0x18, 0xfc, 0xc2, 0x52,
	0xbc, 0xd3, 0x2c, 0xd7, 0xde, 0x02, 0xdc, 0x7b, 0x85, 0x77, 0x8f, 0x22, 0x49, 0xc8, 0x57, 0xe0,
	0x2a, 0x33, 0xd8, 0x6f, 0xd3, 0xb7, 0xf5, 0x9a, 0x9b, 0x16, 0x34, 0xcb, 0x23, 0xd4, 0x66, 0xae,
	0x3c, 0xb0, 0x5b, 0x0a, 0x6b, 0xee, 0x79, 0xd0, 0xbf, 0x57, 0xb8, 0xd6, 0x98, 0x92, 0xd7, 0xd0,
	0x17, 0x1a, 0xd3, 0xfd, 0x0a, 0x3d, 0x53, 0xae, 0xb9, 0xf7, 0x1b, 0x74, 0x7e, 0xcd, 0x9e, 0x90,
	0x7c, 0x80, 0x23, 0x2e, 0x72, 0x3b, 0x39, 0x9a, 0xbd, 0x69, 0xe8, 0xd5, 0xb8, 0xa6, 0x57, 0x22,
	0xf7, 0x8d, 0xcf, 0x9b, 0xc0, 0xd1, 0x95, 0xc8, 0x89, 0x0b, 0x9d, 0x1b, 0xfc, 0x4b, 0x8f, 0x1d,
	0x32, 0x80, 0xae, 0x2f, 0xa2, 0x58, 0x8f, 0x5b, 0xde, 0x1c, 0x46, 0x97, 0xa1, 0x16, 0x99, 0x5c,
	0x66, 0xe9, 0x36, 0x41, 0x8d, 0xe4, 0x3d, 0x1c, 0x87, 0xd5, 0x98, 0xef, 0x5b, 0x18, 0xee, 0xb4,
	0x35, 0xf7, 0x26, 0xe0, 0xde, 0x16, 0x79, 0x18, 0x33, 0x85, 0xff, 0x7d, 0x50, 0x6f, 0x00, 0xfd,
	0x6b, 0xc9, 0xcd, 0xdd, 0x78, 0x00, 0xee, 0x32, 0x93, 0x5a, 0xc8, 0x02, 0x3d, 0x0e, 0xc7, 0x97,
	0x05, 0x17, 0x28, 0x43, 0xfc, 0x03, 0x93, 0x84, 0xbc, 0x85, 0xa1, 0x50, 0x41, 0x18, 0x23, 0xe6,
	0x42, 0x46, 0x36, 0xef, 0xfa, 0x20, 0xd4, 0xb2, 0x52, 0xcc, 0x65, 0x09, 0x15, 0x6c, 0xb2, 0xcc,
	0x4c, 0xb7, 0xed, 0xb4, 0x2b, 0xd4, 0xc2, 0xd6, 0xe4, 0x4b, 0xe8, 0xb1, 0x34, 0x2b, 0xa4, 0xb6,
	0x8c, 0x74, 0xfd, 0xaa, 0xf2, 0xfe, 0xee, 0x42, 0x77, 0x6d, 0xc0, 0xfc, 0xf4, 0x73, 0x9f, 0x83,
	0x9b, 0x57, 0x40, 0x52, 0xb0, 0x0f, 0xde, 0x74, 0x89, 0x35, 0xb3, 0x2b, 0xc7, 0xdf, 0xd9, 0xc9,
	0x4f, 0x30, 0x0c, 0x63, 0x96, 0x07, 0xca, 0x52, 0x45, 0xbf, 0xb0, 0xe9, 0x46, 0x1c, 0x77, 0xe8,
	0xad, 0x1c, 0x1f, 0xc2, 0x3d, 0x88, 0x17, 0x00, 0x11, 0x4b, 0x31, 0x50, 0x06, 0x1d, 0xfa, 0xad,
	0x5d, 0xe0, 0xeb, 0x86, 0x05, 0x76, 0x78, 0xad, 0x1c, 0x7f, 0x10, 0xd5, 0x05, 0x99, 0x43, 0xd7,
	0xf2, 0x44, 0x4f, 0x0e, 0x36, 0x5e, 0xb3, 0xb8, 0x72, 0xfc, 0xd2, 0x4b, 0x3e, 0x42, 0xc7, 0x20,
	0x44, 0x67, 0x36, 0x33, 0x69, 0xce, 0x18, 0xf6, 0x56, 0x8e, 0x6f, 0x9d, 0xe4, 0x03, 0x74, 0xd2,
	0xec, 0x09, 0xe9, 0x8f, 0x36, 0xf1, 0xfa, 0x00, 0x63, 0xc6, 0x6e, 0x6c, 0xe4, 0x06, 0x3e, 0x67,
	0x16, 0xa3, 0xa0, 0xe6, 0x84, 0xfe, 0x6c, 0x93, 0xef, 0x1b, 0x92, 0x2f, 0x81, 0x5b, 0x39, 0xfe,
	0x88, 0xbd, 0x44, 0xf0, 0x1c, 0xdc, 0x6d, 0xc5, 0x17, 0xbd, 0x3d, 0x78, 0xcc, 0x1a, 0x41, 0xf3,
	0x3e, 0xb5, 0xdd, 0x44, 0xc3, 0x8a, 0x39, 0xfa, 0x70, 0x30, 0x5a, 0x63, 0x69, 0xa2, 0xb5, 0x9d,
	0xfc, 0x00, 0x2e, 0x4a, 0x1e, 0x98, 0xab, 0xa6, 0xfc, 0xe0, 0x45, 0x55, 0x70, 0xaf, 0x1c, 0xbf,
	0x8f, 0xe5, 0x90, 0x5c, 0x80, 0xcb, 0x2a, 0xb6, 0xa9, 0xb4, 0xc1, 0xb7, 0x4d, 0xa7, 0xfe, 0x17,
	0xfe, 0x66, 0xdf, 0x3a, 0xb2, 0xe8, 0x43, 0xd7, 0x7e, 0xa6, 0xdf, 0x5d, 0x03, 0xec, 0x3f, 0x31,
	0x32, 0x86, 0xe3, 0xb2, 0xba, 0xb5, 0xd8, 0x8e, 0x1d, 0x42, 0x60, 0x54, 0x2a, 0xf5, 0x52, 0xe3,
	0x16, 0x79, 0x05, 0x9f, 0x95, 0xda, 0x95, 0x50, 0x86, 0xef, 0x71, 0x7b, 0xf1, 0xfd, 0xc3, 0x3c,
	0x12, 0x3a, 0x2e, 0x36, 0xd3, 0x30, 0x4b, 0x4f, 0x15, 0x32, 0x19, 0xb3, 0x08, 0xe5, 0x69, 0xd5,
	0x52, 0x50, 0xb6, 0x74, 0xba, 0x61, 0xe1, 0x23, 0x4a, 0x5e, 0xcb, 0x9b, 0x9e, 0xfd, 0xac, 0xe7,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x54, 0xca, 0x77, 0xda, 0x05, 0x00, 0x00,
}
