---
apiVersion: agones.dev/v1
kind: GameServer
metadata:
  name: local-example-game-server
  generateName: example-game-server-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 7654
  template:
    spec:
      containers:
        - name: simple-game-server
          image: example-game-server:0.0.3
