// @generated by protoc-gen-es v1.9.0
// @generated from file common/info.proto (package endless, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message endless.InfoRequest
 */
export const InfoRequest = /*@__PURE__*/ proto3.makeMessageType(
  "endless.InfoRequest",
  [],
);

/**
 * @generated from message endless.InfoResponse
 */
export const InfoResponse = /*@__PURE__*/ proto3.makeMessageType(
  "endless.InfoResponse",
  () => [
    { no: 1, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "build_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);
