// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proxy/proxy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Endless {

  /// <summary>Holder for reflection information generated from proxy/proxy.proto</summary>
  public static partial class ProxyReflection {

    #region Descriptor
    /// <summary>File descriptor for proxy/proxy.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProxyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFwcm94eS9wcm94eS5wcm90bxIHZW5kbGVzcxoRY29tbW9uL2dhbWUucHJv",
            "dG8yQAoFUHJveHkSNwoER2FtZRIULmVuZGxlc3MuR2FtZVJlcXVlc3QaFS5l",
            "bmRsZXNzLkdhbWVSZXNwb25zZSgBMAFCjwEKC2NvbS5lbmRsZXNzQgpQcm94",
            "eVByb3RvUAFaOGdpdGh1Yi5jb20vc2VhbmhhZ2VuL2VuZGxlc3Nfc3RyZWFt",
            "L2ludGVybmFsL3Byb3RvL3Byb3h5ogIDRVhYqgIHRW5kbGVzc8oCB0VuZGxl",
            "c3PiAhNFbmRsZXNzXEdQQk1ldGFkYXRh6gIHRW5kbGVzc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Endless.GameReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
