name: Pull Request Title Linter
on:
  pull_request:
    types: [edited, opened]
env:
  GO_VERSION: "1.22.0"
jobs:
  test:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go pull request message linter
        uses: masahiro331/go-commitlinter@0.1.1
        env:
          TITLE: ${{ github.event.pull_request.title }}
